### ISSUE TITLE
Is this because unblock-us doesn't support other dynamic dns providers?

### ISSUE THREAD

**Issue by cottsak** [ducas/UpdateUnblockUs#1]

**Comment by ducas** [comment]
Yep. unblock-us simply uses the public IP address of the browsing device to activate the account. If you could configure it with a dynamic dns entry that would be ideal, but it doesn't appear to have the capability.

**Comment by cottsak** [comment]
I think they support DynDns only.. Which is odd.. because using getflix, I only need to specify my domain name - getflix doesn't care about who the dynamic host is provided by.

I would say maybe you should switch (and support local business) but you've already solved your own problem. :)

**Comment by ducas** [comment]
https://support.unblock-us.com/customer/portal/articles/291578-using-dyndns-and-unblock-us

Yep - odd...

On 5 March 2015 at 15:57, Matt Kocaj notifications@github.com wrote:

> I think they support DynDns only.. Which is odd.. because using getflix, I
> only need to specify my domain name - getflix doesn't care about who the
> dynamic host is provided by.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ducas/unblock-me/issues/1#issuecomment-77306670.

## 

Regards,
Ducas Francis
